tinymce.addI18n('cs',{
    "Add to Dictionary": "P\u0159idat do slovn\u00edku",
    "Advanced": "Pokro\u010dil\u00e9",
    "Align center": "Zarovnat na st\u0159ed",
    "Align left": "Zarovnat doleva",
    "Align right": "Zarovnat doprava",
    "Align": "Zarovnat",
    "Alignment": "Zarovn\u00e1n\u00ed",
    "Alternative source": "Alternativn\u00ed zdroj",
    "Anchor": "Kotva",
    "Anchor...": "Kotva...",
    "Anchors": "Kotvy",
    "Apply": "Pou\u017e\u00edt",
    "Author": "Autor",
    "B": "B",
    "Back": "Zp\u011bt",
    "Background color": "Barva pozad\u00ed",
    "Blockquote": "Blokov\u00e1 citace",
    "Blocks": "Bloky",
    "Body": "T\u011blo",
    "Bold": "Tu\u010dn\u00e9",
    "Border color": "Barva r\u00e1me\u010dku",
    "Border": "R\u00e1me\u010dek",
    "Bottom": "Dol\u016f",
    "Brightness": "Jas",
    "Bullet list": "Odr\u00e1\u017eky",
    "Cancel": "Storno",
    "Caption": "Nadpis",
    "Cell padding": "Vnit\u0159n\u00ed okraj bun\u011bk",
    "Cell properties": "Vlastnosti bu\u0148ky",
    "Cell spacing": "Vn\u011bj\u0161\u00ed okraj bun\u011bk",
    "Cell type": "Typ bu\u0148ky",
    "Cell": "Bu\u0148ka",
    "Center": "Na st\u0159ed",
    "Circle": "Kole\u010dko",
    "Clear formatting": "Vymazat form\u00e1tov\u00e1n\u00ed",
    "Close": "Zav\u0159\u00edt",
    "Code": "K\u00f3d",
    "Color levels": "\u00darovn\u011b barev",
    "Color": "Barva",
    "Cols": "Sloupc\u016f",
    "Column group": "Skupina sloupc\u016f",
    "Column": "Sloupec",
    "Constrain proportions": "Zachovat proporce",
    "Contrast": "Kontrast",
    "Copy row": "Kop\u00edrovat \u0159\u00e1dek",
    "Copy": "Kop\u00edrovat",
    "Could not find the specified string.": "Zadan\u00fd \u0159et\u011bzec nebyl nalezen.",
    "Crop": "O\u0159\u00edznout",
    "Current window": "Aktu\u00e1ln\u00ed okno",
    "Custom color": "Vlastn\u00ed barva",
    "Custom...": "Vlastn\u00ed...",
    "Cut row": "Vyjmout \u0159\u00e1dek",
    "Cut": "Vyjmout",
    "Date\/time": "Datum\/\u010das",
    "Decrease indent": "Zmen\u0161it odsazen\u00ed",
    "Default": "V\u00fdchoz\u00ed",
    "Delete column": "Smazat sloupec",
    "Delete row": "Smazat \u0159\u00e1dek",
    "Delete table": "Smazat tabulku",
    "Description": "Popis",
    "Dimensions": "Rozm\u011bry",
    "Disc": "Punt\u00edk",
    "Div": "Div",
    "Document properties": "Vlastnosti dokumentu",
    "Edit image": "Upravit obr\u00e1zek",
    "Edit": "\u00dapravy",
    "Embed": "Vlo\u017eit",
    "Emoticons": "Emotikony",
    "Encoding": "K\u00f3dov\u00e1n\u00ed",
    "File manager": "Spr\u00E1vce soubor\u016F",
    "File": "Soubor",
    "Find and replace": "Naj\u00edt a nahradit",
    "Find and replace...": "Naj\u00edt a nahradit...",
    "Find whole words only": "Hledat pouze cel\u00e1 slova",
    "Find": "Naj\u00edt",
    "Finish": "Ukon\u010dit",
    "Flip horizontally": "P\u0159evr\u00e1tit vodorovn\u011b",
    "Flip vertically": "P\u0159evr\u00e1tit svisle",
    "Font Family": "Rodina p\u00edsma",
    "Font Sizes": "Velikost p\u00edsma",
    "Fonts": "P\u00edsma",
    "Footer": "Pati\u010dka",
    "Format": "Form\u00e1t",
    "Formats": "Form\u00e1ty",
    "Fullscreen": "Na celou obrazovku",
    "G": "G",
    "Gamma": "Gama",
    "General": "Obecn\u00e9",
    "H Align": "Horizont\u00e1ln\u00ed zarovn\u00e1n\u00ed",
    "Header 1": "Nadpis 1",
    "Header 2": "Nadpis 2",
    "Header 3": "Nadpis 3",
    "Header 4": "Nadpis 4",
    "Header 5": "Nadpis 5",
    "Header 6": "Nadpis 6",
    "Header cell": "Hlavi\u010dkov\u00e1 bu\u0148ka",
    "Header": "Hlavi\u010dka",
    "Headers": "Nadpisy",
    "Heading 1": "Nadpis 1",
    "Heading 2": "Nadpis 2",
    "Heading 3": "Nadpis 3",
    "Heading 4": "Nadpis 4",
    "Heading 5": "Nadpis 5",
    "Heading 6": "Nadpis 6",
    "Headings": "Nadpisy",
    "Height": "V\u00fd\u0161ka",
    "Horizontal line": "Vodorovn\u00e1 \u010d\u00e1ra",
    "Horizontal space": "Horizont\u00e1ln\u00ed mezera",
    "Ignore all": "Ignorovat v\u0161e",
    "Ignore": "Ignorovat",
    "Image description": "Popis obr\u00e1zku",
    "Image options": "Vlastnosti obr\u00e1zku",
    "Image...": "Obr\u00e1zek\u2026",
    "Increase indent": "Zv\u011bt\u0161it odsazen\u00ed",
    "Inline": "\u0158\u00e1dkov\u00e9 zobrazen\u00ed (inline)",
    "Insert column after": "Vlo\u017eit sloupec vpravo",
    "Insert column before": "Vlo\u017eit sloupec vlevo",
    "Insert date\/time": "Vlo\u017eit datum \/ \u010das",
    "Insert image": "Vlo\u017eit obr\u00e1zek",
    "Insert link": "Vlo\u017eit odkaz",
    "Insert row after": "Vlo\u017eit \u0159\u00e1dek pod",
    "Insert row before": "Vlo\u017eit \u0159\u00e1dek nad",
    "Insert table": "Vlo\u017eit tabulku",
    "Insert template": "Vlo\u017eit \u0161ablonu",
    "Insert video": "Vlo\u017eit video",
    "Insert": "Vlo\u017eit",
    "Insert\/edit image": "Vlo\u017eit \/ upravit obr\u00e1zek",
    "Insert\/edit link": "Vlo\u017eit \/ upravit odkaz",
    "Insert\/edit video": "Vlo\u017eit \/ upravit video",
    "Invert": "Invertovat",
    "Italic": "Kurz\u00edva",
    "Justify": "Zarovnat do bloku",
    "Keywords": "Kl\u00ed\u010dov\u00e1 slova",
    "Left to right": "Zleva doprava",
    "Left": "Vlevo",
    "Lower Alpha": "Norm\u00e1ln\u00ed \u010d\u00edslov\u00e1n\u00ed",
    "Lower Greek": "Mal\u00e9 p\u00edsmenkov\u00e1n\u00ed",
    "Lower Roman": "Mal\u00e9 \u0159\u00edmsk\u00e9 \u010d\u00edslice",
    "Match case": "Rozli\u0161ovat mal\u00e1 a velk\u00e1 p\u00edsmena",
    "Merge cells": "Slou\u010dit bu\u0148ky",
    "Middle": "Uprost\u0159ed",
    "Name": "N\u00e1zev",
    "New document": "Nov\u00fd dokument",
    "New window": "Nov\u00e9 okno",
    "Next": "Dal\u0161\u00ed",
    "No color": "Bez barvy",
    "Nonbreaking space": "Pevn\u00e1 mezera",
    "None": "\u017d\u00e1dn\u00e9",
    "Numbered list": "\u010c\u00edslov\u00e1n\u00ed",
    "Ok": "OK",
    "Open link in...": "Otev\u0159\u00edt odkaz v...",
    "Orientation": "Transformovat",
    "Page break": "Konec str\u00e1nky",
    "Paragraph": "Odstavec",
    "Paste as text": "Vlo\u017eit jako \u010dist\u00fd text",
    "Paste is now in plain text mode. Contents will now be pasted as plain text until you toggle this option off.": "Je zapnuto vkl\u00e1d\u00e1n\u00ed \u010dist\u00e9ho textu. Dokud nebude tato volba vypnuta, bude ve\u0161ker\u00fd obsah vlo\u017een jako \u010dist\u00fd text.",
    "Paste row after": "Vlo\u017eit \u0159\u00e1dek pod",
    "Paste row before": "Vlo\u017eit \u0159\u00e1dek nad",
    "Paste your embed code below:": "Vlo\u017ete k\u00f3d pro vlo\u017een\u00ed n\u00ed\u017ee:",
    "Paste": "Vlo\u017eit",
    "Poster": "N\u00e1hled",
    "Pre": "Pre",
    "Prev": "P\u0159edchoz\u00ed",
    "Preview": "N\u00e1hled",
    "Print": "Tisk",
    "R": "R",
    "Redo": "Opakovat",
    "Remove link": "Odstranit odkaz",
    "Replace all": "Nahradit v\u0161e",
    "Replace with": "Nahradit za",
    "Replace": "Nahradit",
    "Resize": "Zm\u011bnit velikost",
    "Restore last draft": "Obnovit posledn\u00ed koncept",
    "Rich Text Area. Press ALT-F9 for menu. Press ALT-F10 for toolbar. Press ALT-0 for help": "Editor. Stiskn\u011bte ALT-F9 pro menu, ALT-F10 pro n\u00e1strojovou li\u0161tu a ALT-0 pro n\u00e1pov\u011bdu.",
    "Right to left": "Zprava doleva",
    "Right": "Vpravo",
    "Robots": "Roboti",
    "Rotate clockwise": "Oto\u010dit doprava",
    "Rotate counterclockwise": "Oto\u010dit doleva",
    "Row group": "Skupina \u0159\u00e1dk\u016f",
    "Row properties": "Vlastnosti \u0159\u00e1dku",
    "Row type": "Typ \u0159\u00e1dku",
    "Row": "\u0158\u00e1dek",
    "Rows": "\u0158\u00e1dek",
    "Save (if save plugin activated)": "Ulo\u017eit (pokud je aktivni save plugin)",
    "Save": "Ulo\u017eit",
    "Scope": "Rozsah",
    "Select all": "Vybrat v\u0161e",
    "Select file from file manager": "Vyberte soubor ze spr\u00E1vce soubor\u016F",
    "Sharpen": "Ostrost",
    "Show blocks": "Uk\u00e1zat bloky",
    "Show invisible characters": "Zobrazit speci\u00e1ln\u00ed znaky",
    "Source code": "Zdrojov\u00fd k\u00f3d",
    "Source": "URL",
    "Special character": "Speci\u00e1ln\u00ed znak",
    "Special character...": "Speci\u00e1ln\u00ed znak\u2026",
    "Spell check": "Kontrola pravopisu",
    "Spellcheck": "Kontrola pravopisu",
    "Split cell": "Rozd\u011blit bu\u0148ky",
    "Square": "\u010ctvere\u010dek",
    "Strikethrough": "P\u0159e\u0161krtnut\u00e9",
    "Style": "Styl",
    "Subscript": "Doln\u00ed index",
    "Superscript": "Horn\u00ed index",
    "Table properties": "Vlastnosti tabulky",
    "Table": "Tabulka",
    "Target": "C\u00edl",
    "Templates": "\u0160ablony",
    "Text color": "Barva p\u00edsma",
    "Text to display": "Text k zobrazen\u00ed",
    "The URL you entered seems to be an email address. Do you want to add the required mailto: prefix?": "Zadan\u00e9 URL vypad\u00e1 jako e-mailov\u00e1 adresa. Chcete doplnit povinn\u00fd prefix mailto:?",
    "The URL you entered seems to be an external link. Do you want to add the required http:\/\/ prefix?": "Zadan\u00e9 URL vypad\u00e1 jako odkaz na jin\u00fd web. Chcete doplnit povinn\u00fd prefix http:\/\/?",
    "Title": "Titulek",
    "Tools": "N\u00e1stroje",
    "Top": "Nahoru",
    "Underline": "Podtr\u017een\u00ed",
    "Undo": "Zp\u011bt",
    "Upper Alpha": "velk\u00e9 p\u00edsmenkov\u00e1n\u00ed",
    "Upper Roman": "\u0158\u00edmsk\u00e9 \u010d\u00edslice",
    "Url": "URL",
    "V Align": "Vertik\u00e1ln\u00ed zarovn\u00e1n\u00ed",
    "Vertical space": "Vertik\u00e1ln\u00ed mezera",
    "View": "Zobrazit",
    "Visual aids": "Vizu\u00e1ln\u00ed pom\u016fcky",
    "Whole words": "Pouze cel\u00e1 slova",
    "Width": "\u0160\u00ed\u0159ka",
    "Words: {0}": "Po\u010det slov: {0}",
    "You have unsaved changes are you sure you want to navigate away?": "M\u00e1te neulo\u017een\u00e9 zm\u011bny. Opravdu chcete opustit str\u00e1nku?",
    "Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X\/C\/V keyboard shortcuts instead.": "V\u00e1\u0161 prohl\u00ed\u017ee\u010d nepodporuje p\u0159\u00edm\u00fd p\u0159\u00edstup do schr\u00e1nky. Pou\u017eijte pros\u00edm kl\u00e1vesov\u00e9 zkratky Ctrl+X\/C\/V.",
    "Zoom in": "P\u0159ibl\u00ed\u017eit",
    "Zoom out": "Odd\u00e1lit"
});